### ISSUE TITLE
other features/assorted to-do

### ISSUE THREAD

**Issue by tanho63** [nflverse/nflreadr#7]
- [x] clear cache function
- [x] validate options(nflreadr.prefer) .onAttach
- [x] improve documentation for raw_from_url (i.e. explain intended usage of piping to read_parquet etc)
- [x] warning inside `qs_from_url`'s error message if fail, perhaps also http status code?
- [x] add more boilerplate to readme
- [x] dynastyprocess/data downloads
- [x] add codecov
- [x] data dictionary + vignette for rosters
- [x] add progressr to DESC
- [x] data dictionary + vignette for schedule
- [x] hex logo
- [x] team colours/logos import function
- [x] readme- fix URL
- [x] Document how to use progressr with the raw from_url functions
- [x] data dictionary + vignette for nextgen stats
- [x] load_injuries #14 
- [x] load_depth_charts #15 
- [x] load_trades #18
- [x] load_espn_qbr() #19
- [x] load_snap_counts c/o Ben #17
- [x] load_pfr_adv_passing #17

- [x] load_ff_rankings

Data dictionaries/vignettes missing atm: (these are non-blocking for CRAN but useful to have, imo)
- [ ] load_trades
- [ ] load_injuries
- [ ] load_depth_charts
- [ ] load_espn_qbr

**Comment by tanho63** [comment]
Included much of this in #8. Still need to add data documentation pieces for the main load functions, probably.

**Comment by tanho63** [comment]
Included more in #9.

**Comment by mrcaseb** [comment]
teams colors logos in #11

**Comment by mrcaseb** [comment]
NGS dictionary in #13

**Comment by tanho63** [comment]
----
WE SUBMITTED TO CRAN WOOO
---

Other stuff still welcome to be added for 1.1.0 release

**Comment by tanho63** [comment]
Closing and starting a new issue for datadocs
